# Generated by Django 5.1.6 on 2025-03-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="Username"
                    ),
                ),
                ("password", models.CharField(max_length=256, verbose_name="Password")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                (
                    "user_type",
                    models.IntegerField(
                        choices=[(1, "User"), (2, "Bot")],
                        default=1,
                        verbose_name="User Type",
                    ),
                ),
                (
                    "creation_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation Time"
                    ),
                ),
            ],
        ),
    ]
