# Generated by Django 5.1.6 on 2025-03-02 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_type', models.IntegerField(choices=[(1, 'Public'), (2, 'Private')], default=1, verbose_name='Key Type')),
                ('tool_type', models.IntegerField(choices=[(1, 'GPG')], default=1, verbose_name='Tool Type')),
                ('key', models.TextField()),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Creation Time')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user')),
            ],
        ),
    ]
